CREATE DATABASE noty;

USE noty;

CREATE TABLE accounts (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME
);

CREATE TABLE profiles(
    user_id INT NOT NULL PRIMARY KEY,
    display_name VARCHAR(100) UNIQUE,
    avatar_url VARCHAR(255),
    bio TEXT,
    CONSTRAINT FOREIGN KEY (user_id) REFERENCES accounts (id) ON DELETE CASCADE
);

CREATE TABLE settings (
    user_id INT NOT NULL PRIMARY KEY,
    theme_preference VARCHAR(20) DEFAULT 'light',

    CONSTRAINT FOREIGN KEY (user_id) REFERENCES accounts (id) ON DELETE CASCADE
);

CREATE TABLE sessions (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    token VARCHAR(255) NOT NULL UNIQUE,
    expires_at DATETIME NOT NULL,

    CONSTRAINT FOREIGN KEY (user_id) REFERENCES accounts (id) ON DELETE CASCADE
);

CREATE TABLE folders (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    parent_folder_id INT,
    name VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME,

    CONSTRAINT FOREIGN KEY (user_id) REFERENCES accounts (id) ON DELETE CASCADE,
    CONSTRAINT FOREIGN KEY (parent_folder_id) REFERENCES folders (id) ON DELETE CASCADE
);

CREATE TABLE documents (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    owner_id INT NOT NULL,
    folder_id INT,
    title VARCHAR(255) NOT NULL DEFAULT '',
    content LONGTEXT NOT NULL,
    favorite BOOLEAN DEFAULT FALSE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME,

    CONSTRAINT FOREIGN KEY (owner_id) REFERENCES accounts (id) ON DELETE CASCADE,
    CONSTRAINT FOREIGN KEY (folder_id) REFERENCES folders (id) ON DELETE SET NULL
);

CREATE TABLE tags (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    color VARCHAR(7) NOT NULL DEFAULT '#6b8fa8',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME,

    CONSTRAINT FOREIGN KEY (user_id) REFERENCES accounts (id) ON DELETE CASCADE
);

CREATE TABLE doc_tags (
    doc_id INT NOT NULL,
    tag_id INT NOT NULL,
    PRIMARY KEY (doc_id, tag_id),

    CONSTRAINT FOREIGN KEY (doc_id) REFERENCES documents (id) ON DELETE CASCADE,
    CONSTRAINT FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE
);